/*
 * This file is automatically generated; any changes will be lost. 
 */

#nullable enable

{{#each DataInterface.Usings}}
using {{this}};
{{/each}}

namespace {{DataInterface.Namespace}}
{
    public interface {{DataInterface.Name}}
    {
      {{#each DataClass.Operations}}
      public Task{{#if ReturnType}}<{{ReturnType}}>{{/if}} {{Name}}Async({{#each Parameters}}{{Type}} {{Name}}{{#unless @last}}, {{/unless}}{{/each}});
      {{/each}}
    }
}

#nullable restore
