/*
 * This file is automatically generated; any changes will be lost. 
 */

#nullable enable

{{#each ManagerInterface.Usings}}
using {{this}};
{{/each}}

namespace {{ManagerInterface.Namespace}}
{
    public interface {{ManagerInterface.Name}}
    {
        {{#each Manager.Operations}}
        Task{{#if ReturnType}}<{{ReturnType}}>{{/if}} {{Name}}Async({{#each Parameters}}{{Type}} {{Name}}{{#unless @last}}, {{/unless}}{{/each}});
        {{/each}}
    }
}

#nullable restore